### PR TITLE
Use SymbolicLink rather than Symlink in API

### PR DESCRIPTION
**Pull request by francoisfrisch**
Rename followInsecureSymlinks to followInsecureSymbolicLinks. This
now matches what is writhe in the readme and release notes.

https://github.com/kriskowal/q-io/blob/master/README.md#filetreepath-options--application
https://github.com/kriskowal/q-io/blob/master/CHANGES#L55

### CODE REVIEW

**Comment by francoisfrisch** [comment]
This is would fix montagejs/minit#57

**Comment by Stuk** [comment]
This breaks backwards compatibility and would need a major version to be released, and so the old name should remain supported with a deprecation warning. Unless @kriskowal wants to merge this in with the coming promise-streams 2.0.0 version?

**Comment by kriskowal** [comment]
I think it would be sufficient to retain the old behavior with a deprecation warning then remove the old behavior in 2.0.0.

**Comment by kriskowal** [comment]
I am pretty sure we need to thread this through some HTTP app or another.

**Comment by francoisfrisch** [comment]
There was no threading necessary to make `minit serve -i` work correctly.

**Comment by francoisfrisch** [comment]
The tests don't run on top of master. It looks like the connection is never closed form http.read when there is a 404 error.

**Comment by kriskowal** [comment]
Thanks, @francoisfrisch. Looking into the specs.

**Pull request closed without merging**
