### PR TITLE
Correctly detect path separator on node 0.6.x

### PR DESCRIPTION
**Pull request by SevInf**

### CODE REVIEW

**Comment by Stuk** [comment]
I didn't realise people are still using node 0.6!

I'm not sure if @kriskowal's new promise streams have that back compat either.

**Comment by kriskowal** [comment]
I’ll take it. Whether I will turn on continuous integration on 0.6 is another matter. Thanks.

**Comment by arikon** [comment]
@kriskowal When do you plan to release new version with this fix? ;)

**Comment by kriskowal** [comment]
I’ll post a patch now, `1.10.3`. We should talk about whether to do promise streams in `1.11.0` or `2.0.0`. It is forward compatible by API, but there will be rough edges. If you can try out the `streams` branch at some point to verify that it doesn’t cause you major problems, please do.

**Comment by kriskowal** [comment]
Published `1.10.3`.

**Comment by kriskowal** [comment]
I think I’ll put promise streams in q-io@2.0.0, and upgrade to q@0.10.0 in the same push, so all the pain happens in one push. I realize that some folks are going to be weary from refactoring and will want to have some runway with Q and Q-IO as they stand today.  q-connection will also have a major upgrade on q-io@2.0.0

**Comment by Stuk** [comment]
Sounds good to me!

**Pull request merged**
