### PR TITLE
Promise streams

### PR DESCRIPTION
**Pull request by kriskowal**
All specs pass.

Implemented `Readable` as an abstract interface that provides `forEach`,
`map`, `reduce`, `buffer`, `all`, `copy`, and `read` for any
implementation that provides the asynchronous iterator method, `next`.
Readable makes use of a semaphore `Queue` and a `Pipe` to control
back-pressure based on user-given or methd-specific-default parallelism
limits.

Implemented a `Reader` stream that wraps an array or any object, local
or remote, that provides a `next` method, including iterators and
generator iterators.  Thus, a stream can lazily consume an indefinite
iteration.

Brought in a cleaner implementation of the indefinite promise `Queue`.
This implementation lacks the `close` and `closed` hacks that exist in
the current `q/queue`, which will likely be removed when these changes
get traction, particularly in Q-Connection.

Implemented a `BufferStream`, backed by a `Queue`, that provides both
`Reader` and `Writer` interfaces, as well as an acknoweldgement channel.
`put` returns a promise for when `get` has been consumed.

The Node.js stream reader has been reimplemented based on the latest
rendition of Node.js streams and the new `StreamBuffer`, so promise
streams send back pressure down to the underlying system.  Cosmetic
changes only to `Writer`.

Created a separate mock file stream, which manages an internal `chunks`
array which can be reused on mock file system nodes between reads and
writes.  This turned out to be different enough from `Reader` and
`BufferStream` that a different implementation was needed.  The old
`BufferStream`, originally used by the mock file system has gone away.

Special cases in the HTTP server have been removed, leaving a clean
interface that handles all cases including new streams for bodies.

Ported `WebStream`, by factoring the stream adapter in Q-Connection
together with the new `BufferStream`.  The new streams model connection
closing much more elegantly.  `WebStream` is idempotent and can wrap
`MessageChannel` ports, `WebWorker`, and `WebSocket`.  Q-Connection will
eventually be refactored to take advantage of `WebStream`.

Created `WindowStream`, using code contributed to Q-Connection by
@johnjdalton two years ago.  Window streams are useful for establishing
bidirectional connections between windows and frames.  WindowStream is
not a constructor, but has `listen` and `connect` methods.  `listen`
returns a stream of streams, which can be closed to shut down.
`connect` returns a stream that will buffer and pipe messages when and
if the connection is established.

### CODE REVIEW

**Comment by wmertens** [comment]
:+1: I made a small function that takes an array and a function and turns it into a Q.all but applied on only x items at a time - this is a much nicer way to do it. Love that you can pass Reader an array or a NodeJS stream and it will do the right thing.

One thing though - these are being called a promise stream but they're not NodeJS Streamables. I wonder if perhaps a different name can be used to avoid confusion. Promise Pipeline? Q River? Promise Iterators?

**Comment by kriskowal** [comment]
@wmertens To clarify, there are separate modules/constructors for `Reader` (for iterables) and `NodeReader` (for Node.js readable streams). I am working on porting an adapter from Q-Connection that would wrap up WebSocket and MessagePort (including window and cross frame message ports).

**Comment by kriskowal** [comment]
Further changes to this PR include the addition of WebStream and WindowStream for using Q-IO to adapt some browser stream-like objects into promise streams.

Also, I’ve renamed Buffer to BufferStream to avoid certain kinds of madness in Node.js.

**Comment by wmertens** [comment]
So what do you think is still missing before you put it in master?

**Comment by kriskowal** [comment]
A review from anyone, including running the tests and trying out the `spec/web-stream` demo would suffice, I think. This is potentially destabilizing so some external validation would be great.

**Comment by kriskowal** [comment]
Pushed a rebase and updated the description to reflect the new commit. Some API’s are still in flux. For example, BufferStream’s `put` method now returns a `get` ack promise.

**Comment by kriskowal** [comment]
https://github.com/montagejs/joey specs stall against this branch. Investigating.

**Comment by kriskowal** [comment]
Part of the problem appears to be that `httpServer.stop()` stalls because there are outstanding requests with unread input. This part of the problem is solved by tracking and destroying outstanding requests when the server is stopped. This may or may not be desirable, so I have to think about the API. In the interval, the Joey specs now stall farther down the line and investigation continues.

**Pull request merged**
