### PR TITLE
Add spec for reroot

### PR DESCRIPTION
**Pull request by Stuk**
I'm not actually sure this _is_ what it should do...

### CODE REVIEW

**Comment by kriskowal** [comment]
I agree. Is there a chance we can change the behavior? This behavior was intended to solve traversing into archives that have a prefix path, but I _am_ sure this is not what it should do.

**Comment by Stuk** [comment]
I think it's pretty unlikely that anyone is depending on this behaviour. It's certainly not what I would expect. Just a matter of removing that `if` in `reroot`?

**Comment by kriskowal** [comment]
@Stuk It’s actually a matter of gutting `reroot` so that `return RootFs(self, path)` is all that remains.

**Comment by kriskowal** [comment]
Pushed the change to the simpler behavior, obviating this test and the previous fix.

**Pull request closed without merging**
