### PR TITLE
fix removeTree for directories containing symlinks.

### PR DESCRIPTION
**Pull request by jgadling**
Use lstat() in removeTree so we can identify symlinks properly

### CODE REVIEW

**Comment by Stuk** [comment]
The tests are now failing for when a directory is not a symlink (the [details are here](https://travis-ci.org/kriskowal/q-io/builds/12153373)). Could you add another test for your failing case, and make sure the current ones still pass? You can run them on your own computer with `npm test`. Thanks!

**Comment by kriskowal** [comment]
Curious. I would have assumed that `statLink` would do exactly the same as `stat` except not follow symlinks. I wonder whether it would be wise to solve the problem by modifying `statLink` to conform to that design, or whether that would necessarily cause race problems.

**Comment by kriskowal** [comment]
Oh, no. The problem was in the mock statLink. I’ll land this with the fix to the mock statLink.

**Comment by dcolens** [comment]
minor release update?

**Comment by kriskowal** [comment]
Published 1.10.2

**Pull request merged**
