### PR TITLE
Allow overwrite in move

### PR DESCRIPTION
**Pull request by wmertens**
Add overwrite (bool) parameter to q-fs.move()

### CODE REVIEW

**Comment by kriskowal** [comment]
I’ll take this, but I’m going to factor it into `move` and `moveOver`, with one calling the other with the flag.

**Comment by kriskowal** [comment]
I’m concerned about a few cases, so I’m going over manuals to make sure they’re all accounted for consistently.

Node.js documentation states that `FS.rename` is backed by the underlying rename(2) system call. That is really only meaningful for POSIX. I’m taking the man page from Linux as representative of all the SysV Unices, and MacOS as representative of the BSD Unices.

http://linux.die.net/man/2/rename

http://developer.apple.com/library/ios/#documentation/system/conceptual/manpages_iphoneos/man2/rename.2.html

I have no idea about Windows, but I fear it is not consistent.

The cases to note are cross-device rename, and renaming directories.

The gist I’m getting is that cross-device rename is not permitted, so for that case you have to fall back to copy(old, new)+remove(old) or copyTree/removeTree—manually. The Unices seem to agree.

For renaming directories, it appears that the Unices also agree. Renaming a directory to a target location is permitted as long as the target directory was empty, so renaming does not imply a removeTree on the target dir.

I had a fear that some versions would interpret moving a directory _either_ as (a) replacing the target directory or (b) moving the source directory into the target directory. That fear does not appear to be substantiated by MacOS or Lunix rename(2).

Still wondering about what Windows does, but I think I will trust, based on the Node.js man, that any deviation from rename(2) would be a bug in Node and rectified there.

**Comment by kriskowal** [comment]
I have changed my mind. I’m going to simply relax the restriction in overwriting, trusting to the system call to behave consistently.

Part of the reason is the exists check is advisory at best, a nuisance at worst. There is a window between the exists check and the rename call where the state on the file system could change, invalidating the judgement. The operating system really is the only level at which one can safely perform an exists check before committing the change, and we simply are not writing at that level.

**Comment by kriskowal** [comment]
I’ve published v1.8.0 with the relaxation of the overwrite requirement

**Comment by wmertens** [comment]
makes sense

**Pull request merged**
